from ..base import Camera


class CanonCamera(Camera):
    _DATABASE = {
        "Canon_EOS_Ra": {
            "brand": "Canon",
            "name": "EOS Ra",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 660,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 6720,
            "height": 4480,
            "pixel_size_um": 5.36,
        },
        "Canon_EOS_6D_II": {
            "brand": "Canon",
            "name": "EOS 6D II",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 765,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 24.0,
            "width": 6240,
            "height": 4160,
            "pixel_size_um": 5.75,
        },
        "Canon_EOS_5D_IV": {
            "brand": "Canon",
            "name": "EOS 5D IV",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 890,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 6720,
            "height": 4480,
            "pixel_size_um": 5.36,
        },
        "Canon_EOS_5D_III": {
            "brand": "Canon",
            "name": "EOS 5D III",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 860,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 5760,
            "height": 3840,
            "pixel_size_um": 6.25,
        },
        "Canon_EOS_60Da": {
            "brand": "Canon",
            "name": "EOS 60Da",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 675,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_1000Da": {
            "brand": "Canon",
            "name": "EOS 1000Da",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 480,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 3888,
            "height": 2592,
            "pixel_size_um": 5.7,
        },
        "Canon_EOS_2000D": {
            "brand": "Canon",
            "name": "EOS 2000D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 475,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_850D": {
            "brand": "Canon",
            "name": "EOS 850D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 515,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_90D": {
            "brand": "Canon",
            "name": "EOS 90D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 701,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.8,
            "width": 6960,
            "height": 4640,
            "pixel_size_um": 3.2,
        },
        "Canon_EOS_80D": {
            "brand": "Canon",
            "name": "EOS 80D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 730,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_77D": {
            "brand": "Canon",
            "name": "EOS 77D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 540,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_4000D": {
            "brand": "Canon",
            "name": "EOS 4000D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 436,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_750D": {
            "brand": "Canon",
            "name": "EOS 750D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 555,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_700D": {
            "brand": "Canon",
            "name": "EOS 700D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 580,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_650D": {
            "brand": "Canon",
            "name": "EOS 650D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 575,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_600D": {
            "brand": "Canon",
            "name": "EOS 600D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 570,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_550D": {
            "brand": "Canon",
            "name": "EOS 550D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 530,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_450D": {
            "brand": "Canon",
            "name": "EOS 450D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 475,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 4272,
            "height": 2848,
            "pixel_size_um": 5.2,
        },
        "Canon_EOS_350D": {
            "brand": "Canon",
            "name": "EOS 350D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 485,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 3456,
            "height": 2304,
            "pixel_size_um": 6.4,
        },
        "Canon_EOS_1100D": {
            "brand": "Canon",
            "name": "EOS 1100D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 495,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.7,
            "width": 4272,
            "height": 2848,
            "pixel_size_um": 5.2,
        },
        "Canon_EOS_7D_II": {
            "brand": "Canon",
            "name": "EOS 7D II",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 910,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.4,
            "sensor_height_mm": 15.0,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 4.1,
        },
        "Canon_EOS_6D": {
            "brand": "Canon",
            "name": "EOS 6D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 770,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.8,
            "sensor_height_mm": 23.9,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 6.54,
        },
        "Canon_EOS_5D_II": {
            "brand": "Canon",
            "name": "EOS 5D II",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 810,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 5616,
            "height": 3744,
            "pixel_size_um": 6.4,
        },
        "Canon_EOS_1200D": {
            "brand": "Canon",
            "name": "EOS 1200D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 480,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_R": {
            "brand": "Canon",
            "name": "EOS R",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 660,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 6720,
            "height": 4480,
            "pixel_size_um": 5.36,
        },
        "Canon_EOS_R5": {
            "brand": "Canon",
            "name": "EOS R5",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 738,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 8192,
            "height": 5464,
            "pixel_size_um": 4.4,
        },
        "Canon_EOS_R5_II": {
            "brand": "Canon",
            "name": "EOS R5 II",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 746,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 8192,
            "height": 5464,
            "pixel_size_um": 4.4,
        },
        "Canon_EOS_R6": {
            "brand": "Canon",
            "name": "EOS R6",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 680,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 23.9,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 6.56,
        },
        "Canon_EOS_R6_II": {
            "brand": "Canon",
            "name": "EOS R6 II",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 670,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 23.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 6.0,
        },
        "Canon_EOS_R7": {
            "brand": "Canon",
            "name": "EOS R7",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 612,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.8,
            "width": 6960,
            "height": 4640,
            "pixel_size_um": 3.2,
        },
        "Canon_EOS_R8": {
            "brand": "Canon",
            "name": "EOS R8",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 461,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 23.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 6.0,
        },
        "Canon_EOS_R10": {
            "brand": "Canon",
            "name": "EOS R10",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 429,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_R50": {
            "brand": "Canon",
            "name": "EOS R50",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 375,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_R100": {
            "brand": "Canon",
            "name": "EOS R100",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 356,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_RP": {
            "brand": "Canon",
            "name": "EOS RP",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 485,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 24.0,
            "width": 6240,
            "height": 4160,
            "pixel_size_um": 5.75,
        },
        "Canon_EOS_R3": {
            "brand": "Canon",
            "name": "EOS R3",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 1015,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 6.0,
        },
        "Canon_EOS_R6_III": {
            "brand": "Canon",
            "name": "EOS R6 III",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 680,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 23.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 6.0,
        },
        "Canon_EOS_R1": {
            "brand": "Canon",
            "name": "EOS R1",
            "type": "type_dslr",
            "optical_length": 20,
            "mass": 1115,
            "tside_thread": "EOS R",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 6.0,
        },
        "Canon_EOS_M50_II": {
            "brand": "Canon",
            "name": "EOS M50 II",
            "type": "type_dslr",
            "optical_length": 18,
            "mass": 387,
            "tside_thread": "EOS M",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_20Da": {
            "brand": "Canon",
            "name": "EOS 20Da",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 685,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.5,
            "sensor_height_mm": 15.0,
            "width": 3504,
            "height": 2336,
            "pixel_size_um": 6.4,
        },
        "Canon_EOS_300D": {
            "brand": "Canon",
            "name": "EOS 300D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 560,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.7,
            "sensor_height_mm": 15.1,
            "width": 3072,
            "height": 2048,
            "pixel_size_um": 7.4,
        },
        "Canon_EOS_400D": {
            "brand": "Canon",
            "name": "EOS 400D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 510,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 3888,
            "height": 2592,
            "pixel_size_um": 5.7,
        },
        "Canon_EOS_500D": {
            "brand": "Canon",
            "name": "EOS 500D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 480,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 4752,
            "height": 3168,
            "pixel_size_um": 4.7,
        },
        "Canon_EOS_1000D": {
            "brand": "Canon",
            "name": "EOS 1000D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 450,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 3888,
            "height": 2592,
            "pixel_size_um": 5.7,
        },
        "Canon_EOS_1300D": {
            "brand": "Canon",
            "name": "EOS 1300D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 485,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_M6_II": {
            "brand": "Canon",
            "name": "EOS M6 II",
            "type": "type_dslr",
            "optical_length": 18,
            "mass": 408,
            "tside_thread": "EOS M",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.8,
            "width": 6960,
            "height": 4640,
            "pixel_size_um": 3.2,
        },
        "Canon_EOS_200D": {
            "brand": "Canon",
            "name": "EOS 200D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 453,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_250D": {
            "brand": "Canon",
            "name": "EOS 250D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 449,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_M200": {
            "brand": "Canon",
            "name": "EOS M200",
            "type": "type_dslr",
            "optical_length": 18,
            "mass": 299,
            "tside_thread": "EOS M",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 6000,
            "height": 4000,
            "pixel_size_um": 3.72,
        },
        "Canon_EOS_70D": {
            "brand": "Canon",
            "name": "EOS 70D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 755,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.5,
            "sensor_height_mm": 15.0,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 4.1,
        },
        "Canon_EOS_5DS_R": {
            "brand": "Canon",
            "name": "EOS 5DS R",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 930,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 8688,
            "height": 5792,
            "pixel_size_um": 4.14,
        },
        "Canon_EOS_5DS": {
            "brand": "Canon",
            "name": "EOS 5DS",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 930,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 8688,
            "height": 5792,
            "pixel_size_um": 4.14,
        },
        "Canon_EOS_1DX_III": {
            "brand": "Canon",
            "name": "EOS 1DX III",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 1440,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 36.0,
            "sensor_height_mm": 24.0,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 6.58,
        },
        "Canon_EOS_1DX_II": {
            "brand": "Canon",
            "name": "EOS 1DX II",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 1530,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.9,
            "sensor_height_mm": 23.9,
            "width": 5472,
            "height": 3648,
            "pixel_size_um": 6.56,
        },
        "Canon_EOS_5D": {
            "brand": "Canon",
            "name": "EOS 5D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 810,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 35.8,
            "sensor_height_mm": 23.9,
            "width": 4368,
            "height": 2912,
            "pixel_size_um": 8.2,
        },
        "Canon_EOS_100D": {
            "brand": "Canon",
            "name": "EOS 100D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 407,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 5184,
            "height": 3456,
            "pixel_size_um": 4.3,
        },
        "Canon_EOS_40D": {
            "brand": "Canon",
            "name": "EOS 40D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 822,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.2,
            "sensor_height_mm": 14.8,
            "width": 3888,
            "height": 2592,
            "pixel_size_um": 5.7,
        },
        "Canon_EOS_50D": {
            "brand": "Canon",
            "name": "EOS 50D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 822,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.3,
            "sensor_height_mm": 14.9,
            "width": 4752,
            "height": 3168,
            "pixel_size_um": 4.7,
        },
        "Canon_EOS_30D": {
            "brand": "Canon",
            "name": "EOS 30D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 784,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.5,
            "sensor_height_mm": 15.0,
            "width": 3504,
            "height": 2336,
            "pixel_size_um": 6.4,
        },
        "Canon_EOS_20D": {
            "brand": "Canon",
            "name": "EOS 20D",
            "type": "type_dslr",
            "optical_length": 44,
            "mass": 770,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "",
            "cside_gender": "",
            "reversible": False,
            "bf_role": "end",
            "sensor_width_mm": 22.5,
            "sensor_height_mm": 15.0,
            "width": 3504,
            "height": 2336,
            "pixel_size_um": 6.4,
        },
    }

    @classmethod
    def Canon_EOS_Ra(cls):
        return cls.from_database(cls._DATABASE['Canon_EOS_Ra'])

    def Canon_EOS_30D(cls):
        return cls.from_database(cls._DATABASE['Canon_EOS_30D'])

    @classmethod
    def Canon_EOS_20D(cls):
        return cls.from_database(cls._DATABASE['Canon_EOS_20D'])
