from ..base import Eyepiece

class MaxvisionEyepiece(Eyepiece):
    _DATABASE = {       'Maxvision_13mm_82': {       'bf_role': '',
                                     'brand': 'Maxvision',
                                     'cside_gender': '',
                                     'cside_thread': '',
                                     'field_of_view_deg': 82.0,
                                     'focal_length_mm': 13.0,
                                     'mass': 350,
                                     'name': '13mm 82°',
                                     'optical_length': 0,
                                     'reversible': False,
                                     'tside_gender': 'Male',
                                     'tside_thread': '2"',
                                     'type': 'type_eyepiece'},
        'Maxvision_20mm_82': {       'bf_role': '',
                                     'brand': 'Maxvision',
                                     'cside_gender': '',
                                     'cside_thread': '',
                                     'field_of_view_deg': 82.0,
                                     'focal_length_mm': 20.0,
                                     'mass': 500,
                                     'name': '20mm 82°',
                                     'optical_length': 0,
                                     'reversible': False,
                                     'tside_gender': 'Male',
                                     'tside_thread': '2"',
                                     'type': 'type_eyepiece'},
        'Maxvision_28mm_82': {       'bf_role': '',
                                     'brand': 'Maxvision',
                                     'cside_gender': '',
                                     'cside_thread': '',
                                     'field_of_view_deg': 82.0,
                                     'focal_length_mm': 28.0,
                                     'mass': 700,
                                     'name': '28mm 82°',
                                     'optical_length': 0,
                                     'reversible': False,
                                     'tside_gender': 'Male',
                                     'tside_thread': '2"',
                                     'type': 'type_eyepiece'},
        'Maxvision_3_5mm_82': {       'bf_role': '',
                                      'brand': 'Maxvision',
                                      'cside_gender': '',
                                      'cside_thread': '',
                                      'field_of_view_deg': 82.0,
                                      'focal_length_mm': 3.5,
                                      'mass': 280,
                                      'name': '3.5mm 82°',
                                      'optical_length': 0,
                                      'reversible': False,
                                      'tside_gender': 'Male',
                                      'tside_thread': '1.25"',
                                      'type': 'type_eyepiece'},
        'Maxvision_6mm_82': {       'bf_role': '',
                                    'brand': 'Maxvision',
                                    'cside_gender': '',
                                    'cside_thread': '',
                                    'field_of_view_deg': 82.0,
                                    'focal_length_mm': 6.0,
                                    'mass': 300,
                                    'name': '6mm 82°',
                                    'optical_length': 0,
                                    'reversible': False,
                                    'tside_gender': 'Male',
                                    'tside_thread': '1.25"',
                                    'type': 'type_eyepiece'},
        'Maxvision_9mm_82': {       'bf_role': '',
                                    'brand': 'Maxvision',
                                    'cside_gender': '',
                                    'cside_thread': '',
                                    'field_of_view_deg': 82.0,
                                    'focal_length_mm': 9.0,
                                    'mass': 320,
                                    'name': '9mm 82°',
                                    'optical_length': 0,
                                    'reversible': False,
                                    'tside_gender': 'Male',
                                    'tside_thread': '1.25"',
                                    'type': 'type_eyepiece'}}