from apts.i18n import gettext_ as _

constellation_map = {
    "And": _("Andromeda"),
    "Ant": _("Antlia"),
    "Aps": _("Apus"),
    "Aqr": _("Aquarius"),
    "Aql": _("Aquila"),
    "Ara": _("Ara"),
    "Ari": _("Aries"),
    "Aur": _("Auriga"),
    "Boo": _("Boötes"),
    "Cae": _("Caelum"),
    "Cam": _("Camelopardalis"),
    "Cnc": _("Cancer"),
    "CVn": _("Canes Venatici"),
    "CMa": _("Canis Major"),
    "CMi": _("Canis Minor"),
    "Cap": _("Capricornus"),
    "Car": _("Carina"),
    "Cas": _("Cassiopeia"),
    "Cen": _("Centaurus"),
    "Cep": _("Cepheus"),
    "Cet": _("Cetus"),
    "Cha": _("Chamaeleon"),
    "Cir": _("Circinus"),
    "Col": _("Columba"),
    "Com": _("Coma Berenices"),
    "CrA": _("Corona Australis"),
    "CrB": _("Corona Borealis"),
    "Crv": _("Corvus"),
    "Crt": _("Crater"),
    "Cru": _("Crux"),
    "Cyg": _("Cygnus"),
    "Del": _("Delphinus"),
    "Dor": _("Dorado"),
    "Dra": _("Draco"),
    "Equ": _("Equuleus"),
    "Eri": _("Eridanus"),
    "For": _("Fornax"),
    "Gem": _("Gemini"),
    "Gru": _("Grus"),
    "Her": _("Hercules"),
    "Hor": _("Horologium"),
    "Hya": _("Hydra"),
    "Hyi": _("Hydrus"),
    "Ind": _("Indus"),
    "Lac": _("Lacerta"),
    "Leo": _("Leo"),
    "LMi": _("Leo Minor"),
    "Lep": _("Lepus"),
    "Lib": _("Libra"),
    "Lup": _("Lupus"),
    "Lyn": _("Lynx"),
    "Lyr": _("Lyra"),
    "Men": _("Mensa"),
    "Mic": _("Microscopium"),
    "Mon": _("Monoceros"),
    "Mus": _("Musca"),
    "Nor": _("Norma"),
    "Oct": _("Octans"),
    "Oph": _("Ophiuchus"),
    "Ori": _("Orion"),
    "Pav": _("Pavo"),
    "Peg": _("Pegasus"),
    "Per": _("Perseus"),
    "Phe": _("Phoenix"),
    "Pic": _("Pictor"),
    "Psc": _("Pisces"),
    "PsA": _("Piscis Austrinus"),
    "Pup": _("Puppis"),
    "Pyx": _("Pyxis"),
    "Ret": _("Reticulum"),
    "Sge": _("Sagitta"),
    "Sgr": _("Sagittarius"),
    "Sco": _("Scorpius"),
    "Scl": _("Sculptor"),
    "Sct": _("Scutum"),
    "Ser": _("Serpens"),
    "Sex": _("Sextans"),
    "Tau": _("Taurus"),
    "Tel": _("Telescopium"),
    "Tri": _("Triangulum"),
    "TrA": _("Triangulum Australe"),
    "Tuc": _("Tucana"),
    "UMa": _("Ursa Major"),
    "UMi": _("Ursa Minor"),
    "Vel": _("Vela"),
    "Vir": _("Virgo"),
    "Vol": _("Volans"),
    "Vul": _("Vulpecula")
}
