class EquipmentTableLabels:
    DAWES_LIMIT = "Dawes' limit"
    EXIT_PUPIL = "Exit pupil"
    LABEL = "Label"
    TYPE = "Type"
    ZOOM = "Zoom"
    USEFUL_ZOOM = "Useful"
    FOV = "FoV"
    RANGE = "Range"
    BRIGHTNESS = "Brightness"
    ELEMENTS = "Elements"
    FLIPPED_HORIZONTALLY = "Flipped Horizontally"
    FLIPPED_VERTICALLY = "Flipped Vertically"
    PIXEL_SCALE = "Pixel scale"
    NPF_RULE = "NPF Rule (s)"
    RULE_OF_500 = "Rule of 500 (s)"
    SAMPLING = "Sampling"
    IS_NAKED_EYE = "_is_naked_eye"
