class EquipmentTableLabels:
    DAWES_LIMIT = "Dawes' limit"
    EXIT_PUPIL = "Exit pupil"
    LABEL = "Label"
    TYPE = "Type"
    ZOOM = "Zoom"
    USEFUL_ZOOM = "Useful"
    FOV = "FoV"
    RANGE = "Range"
    BRIGHTNESS = "Brightness"
    ELEMENTS = "Elements"
    FLIPPED_HORIZONTALLY = "Flipped Horizontally"
    FLIPPED_VERTICALLY = "Flipped Vertically"
    IS_NAKED_EYE = "_is_naked_eye"
