DATABASE = {
        "Baader_M42_Spacer_0_3mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_2mm": {
            "brand": "Baader",
            "name": "M42 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_3mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_2mm": {
            "brand": "Baader",
            "name": "M48 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_2mm": {
            "brand": "Baader",
            "name": "M54 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_2mm": {
            "brand": "Baader",
            "name": "M68 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_1mm": {
            "brand": "Baader",
            "name": "M72 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_2mm": {
            "brand": "Baader",
            "name": "M72 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M82_Spacer_2mm": {
            "brand": "Baader",
            "name": "M82 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 16,
            "tside_thread": "M82",
            "tside_gender": "",
            "cside_thread": "M82",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_15mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.15mm",
            "type": "type_spacer",
            "optical_length": 0.15,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M56_Spacer_1mm": {
            "brand": "Baader",
            "name": "M56 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M56_Spacer_2mm": {
            "brand": "Baader",
            "name": "M56 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M63_Spacer_1mm": {
            "brand": "Baader",
            "name": "M63 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M63_Spacer_2mm": {
            "brand": "Baader",
            "name": "M63 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_25mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_35mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.35mm",
            "type": "type_spacer",
            "optical_length": 0.35,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_6mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_75mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_8mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_0_9mm": {
            "brand": "Baader",
            "name": "M42 Spacer 0.9mm",
            "type": "type_spacer",
            "optical_length": 0.9,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_2mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.2mm",
            "type": "type_spacer",
            "optical_length": 1.2,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_8mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.8mm",
            "type": "type_spacer",
            "optical_length": 1.8,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_15mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.15mm",
            "type": "type_spacer",
            "optical_length": 0.15,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_25mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_35mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.35mm",
            "type": "type_spacer",
            "optical_length": 0.35,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_6mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_75mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_8mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_0_9mm": {
            "brand": "Baader",
            "name": "M48 Spacer 0.9mm",
            "type": "type_spacer",
            "optical_length": 0.9,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_2mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.2mm",
            "type": "type_spacer",
            "optical_length": 1.2,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_8mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.8mm",
            "type": "type_spacer",
            "optical_length": 1.8,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_25mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_3mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_6mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_75mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_0_8mm": {
            "brand": "Baader",
            "name": "M54 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_2mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.2mm",
            "type": "type_spacer",
            "optical_length": 1.2,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_25mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_3mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_6mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_75mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_0_8mm": {
            "brand": "Baader",
            "name": "M68 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_2mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.2mm",
            "type": "type_spacer",
            "optical_length": 1.2,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_1mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_3mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_7mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M42_Spacer_1_9mm": {
            "brand": "Baader",
            "name": "M42 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_1mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_3mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_7mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M48_Spacer_1_9mm": {
            "brand": "Baader",
            "name": "M48 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_1mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_3mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_7mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M54_Spacer_1_9mm": {
            "brand": "Baader",
            "name": "M54 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_1mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_3mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_7mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M68_Spacer_1_9mm": {
            "brand": "Baader",
            "name": "M68 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 11,
            "tside_thread": "M68",
            "tside_gender": "",
            "cside_thread": "M68",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_0_3mm": {
            "brand": "Baader",
            "name": "M72 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M72 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_0_7mm": {
            "brand": "Baader",
            "name": "M72 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_0_8mm": {
            "brand": "Baader",
            "name": "M72 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_1_1mm": {
            "brand": "Baader",
            "name": "M72 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_1_3mm": {
            "brand": "Baader",
            "name": "M72 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M72 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M72_Spacer_1_7mm": {
            "brand": "Baader",
            "name": "M72 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 13,
            "tside_thread": "M72",
            "tside_gender": "",
            "cside_thread": "M72",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M82_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M82 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 16,
            "tside_thread": "M82",
            "tside_gender": "",
            "cside_thread": "M82",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M82_Spacer_0_7mm": {
            "brand": "Baader",
            "name": "M82 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 16,
            "tside_thread": "M82",
            "tside_gender": "",
            "cside_thread": "M82",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M82_Spacer_1mm": {
            "brand": "Baader",
            "name": "M82 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 16,
            "tside_thread": "M82",
            "tside_gender": "",
            "cside_thread": "M82",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M82_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M82 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 16,
            "tside_thread": "M82",
            "tside_gender": "",
            "cside_thread": "M82",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M92_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M92 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 19,
            "tside_thread": "M92",
            "tside_gender": "",
            "cside_thread": "M92",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M92_Spacer_1mm": {
            "brand": "Baader",
            "name": "M92 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 19,
            "tside_thread": "M92",
            "tside_gender": "",
            "cside_thread": "M92",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M92_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M92 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 19,
            "tside_thread": "M92",
            "tside_gender": "",
            "cside_thread": "M92",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M92_Spacer_2mm": {
            "brand": "Baader",
            "name": "M92 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 19,
            "tside_thread": "M92",
            "tside_gender": "",
            "cside_thread": "M92",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_SC_Schmidt_Cassegrain_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "SC (Schmidt-Cassegrain) Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_SC_Schmidt_Cassegrain_Spacer_1mm": {
            "brand": "Baader",
            "name": "SC (Schmidt-Cassegrain) Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_SC_Schmidt_Cassegrain_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "SC (Schmidt-Cassegrain) Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_SC_Schmidt_Cassegrain_Spacer_2mm": {
            "brand": "Baader",
            "name": "SC (Schmidt-Cassegrain) Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_1_25_Spacer_0_5mm": {
            "brand": "Baader",
            "name": '1.25" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_1_25_Spacer_1mm": {
            "brand": "Baader",
            "name": '1.25" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_1_25_Spacer_1_5mm": {
            "brand": "Baader",
            "name": '1.25" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_1_25_Spacer_2mm": {
            "brand": "Baader",
            "name": '1.25" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_2_Spacer_0_5mm": {
            "brand": "Baader",
            "name": '2" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_2_Spacer_1mm": {
            "brand": "Baader",
            "name": '2" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_2_Spacer_1_5mm": {
            "brand": "Baader",
            "name": '2" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_2_Spacer_2mm": {
            "brand": "Baader",
            "name": '2" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M84_Spacer_0_5mm": {
            "brand": "Baader",
            "name": "M84 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 15,
            "tside_thread": "M84",
            "tside_gender": "",
            "cside_thread": "M84",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M84_Spacer_1mm": {
            "brand": "Baader",
            "name": "M84 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 15,
            "tside_thread": "M84",
            "tside_gender": "",
            "cside_thread": "M84",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M84_Spacer_1_5mm": {
            "brand": "Baader",
            "name": "M84 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 15,
            "tside_thread": "M84",
            "tside_gender": "",
            "cside_thread": "M84",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_M84_Spacer_2mm": {
            "brand": "Baader",
            "name": "M84 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 15,
            "tside_thread": "M84",
            "tside_gender": "",
            "cside_thread": "M84",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Baader_2_to_1_25_Reducer": {
            "brand": "Baader",
            "name": '2" to 1.25" Reducer Adapter',
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 80,
            "tside_thread": '2"',
            "tside_gender": "Male",
            "cside_thread": '1.25"',
            "cside_gender": "Female",
            "reversible": False,
            "bf_role": "",
        },
    }
