DATABASE = {
        "Celestron_M42_Spacer_2mm": {
            "brand": "Celestron",
            "name": "M42 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M48_Spacer_2mm": {
            "brand": "Celestron",
            "name": "M48 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M42_Spacer_1mm": {
            "brand": "Celestron",
            "name": "M42 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M48_Spacer_1mm": {
            "brand": "Celestron",
            "name": "M48 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M54_Spacer_2mm": {
            "brand": "Celestron",
            "name": "M54 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M42_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": "M42 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M42_Spacer_0_7mm": {
            "brand": "Celestron",
            "name": "M42 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M42_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": "M42 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M48_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": "M48 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M48_Spacer_0_7mm": {
            "brand": "Celestron",
            "name": "M48 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M48_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": "M48 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 7,
            "tside_thread": "M48",
            "tside_gender": "",
            "cside_thread": "M48",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M54_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": "M54 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_M54_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": "M54 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_SC_Schmidt_Cassegrain_Spacer_1mm": {
            "brand": "Celestron",
            "name": "SC (Schmidt-Cassegrain) Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_SC_Schmidt_Cassegrain_Spacer_2mm": {
            "brand": "Celestron",
            "name": "SC (Schmidt-Cassegrain) Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_SC_Schmidt_Cassegrain_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": "SC (Schmidt-Cassegrain) Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_SC_Schmidt_Cassegrain_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": "SC (Schmidt-Cassegrain) Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_1_25_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": '1.25" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_1_25_Spacer_1mm": {
            "brand": "Celestron",
            "name": '1.25" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_1_25_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": '1.25" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_1_25_Spacer_2mm": {
            "brand": "Celestron",
            "name": '1.25" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_2_Spacer_0_5mm": {
            "brand": "Celestron",
            "name": '2" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_2_Spacer_1mm": {
            "brand": "Celestron",
            "name": '2" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_2_Spacer_1_5mm": {
            "brand": "Celestron",
            "name": '2" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_2_Spacer_2mm": {
            "brand": "Celestron",
            "name": '2" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
        "Celestron_SC_to_M42_Adapter": {
            "brand": "Celestron",
            "name": "SC to M42 Adapter",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 50,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
        "Celestron_SC_Visual_Back_2": {
            "brand": "Celestron",
            "name": 'SC Visual Back 2"',
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 150,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Female",
            "reversible": False,
            "bf_role": "",
        },
        "Celestron_SC_Visual_Back_1_25": {
            "brand": "Celestron",
            "name": 'SC Visual Back 1.25"',
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 100,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Female",
            "reversible": False,
            "bf_role": "",
        },
    }
