ADAPTERS = {
    "Generic_T2_Ring_EOS": {
            "brand": "Generic",
            "name": "T2 Ring EOS",
            "type": "type_adapter",
            "optical_length": 10.5,
            "mass": 30,
            "tside_thread": "EOS",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Canon_RF": {
            "brand": "Generic",
            "name": "T2 Ring Canon RF",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 25,
            "tside_thread": "Canon RF",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Nikon_F": {
            "brand": "Generic",
            "name": "T2 Ring Nikon F",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 30,
            "tside_thread": "Nikon F",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Nikon_Z": {
            "brand": "Generic",
            "name": "T2 Ring Nikon Z",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 25,
            "tside_thread": "Nikon Z",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Sony_E": {
            "brand": "Generic",
            "name": "T2 Ring Sony E",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "Sony E",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Fuji_X": {
            "brand": "Generic",
            "name": "T2 Ring Fuji X",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "Fuji X",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_MFT": {
            "brand": "Generic",
            "name": "T2 Ring MFT",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "MFT",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T2_Ring_Pentax_K": {
            "brand": "Generic",
            "name": "T2 Ring Pentax K",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 30,
            "tside_thread": "Pentax K",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_1_25_CS_Adapter": {
            "brand": "Generic",
            "name": '1.25"→CS Adapter',
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 10,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": "CS",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_2_1_25_Adapter": {
            "brand": "Generic",
            "name": '2"→1.25" Adapter',
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 15,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "outputs": [('1.25"', "Male"), ("T2", "Male")],
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Eyepiece_Projection_Adapter_1_25": {
            "brand": "Generic",
            "name": 'Eyepiece Projection Adapter (1.25")',
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 60,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 5mm',
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 7,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_10mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 10mm',
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 11,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_15mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 15mm',
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 15,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_20mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 20mm',
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 19,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_25mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 25mm',
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 23,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_30mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 30mm',
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 27,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 5mm',
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 12,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_10mm": {
            "brand": "Generic",
            "name": '2" Spacer 10mm',
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 16,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_15mm": {
            "brand": "Generic",
            "name": '2" Spacer 15mm',
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 20,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_20mm": {
            "brand": "Generic",
            "name": '2" Spacer 20mm',
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 24,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_25mm": {
            "brand": "Generic",
            "name": '2" Spacer 25mm',
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 28,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_30mm": {
            "brand": "Generic",
            "name": '2" Spacer 30mm',
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 32,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_2_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 2.5mm',
            "type": "type_adapter",
            "optical_length": 2.5,
            "mass": 5,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_3mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 3mm',
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 5,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_3_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 3.5mm',
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 5,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_4mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 4mm',
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 6,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_4_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 4.5mm',
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 6,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_5_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 5.5mm',
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 7,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_6mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 6mm',
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 7,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_6_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 6.5mm',
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 8,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_7mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 7mm',
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 8,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_7_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 7.5mm',
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 9,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_8mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 8mm',
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 9,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_8_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 8.5mm',
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 9,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_9mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 9mm',
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 10,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_9_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 9.5mm',
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 10,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_11mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 11mm',
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 11,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_12mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 12mm',
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 12,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_13mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 13mm',
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 13,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_14mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 14mm',
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 14,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_16mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 16mm',
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 15,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_17mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 17mm',
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 16,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_18mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 18mm',
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 17,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_22mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 22mm',
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 20,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_2_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 2.5mm',
            "type": "type_adapter",
            "optical_length": 2.5,
            "mass": 10,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_3mm": {
            "brand": "Generic",
            "name": '2" Spacer 3mm',
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 10,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_3_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 3.5mm',
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 10,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_4mm": {
            "brand": "Generic",
            "name": '2" Spacer 4mm',
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 11,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_4_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 4.5mm',
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 11,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_5_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 5.5mm',
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 12,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_6mm": {
            "brand": "Generic",
            "name": '2" Spacer 6mm',
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 12,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_6_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 6.5mm',
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 13,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_7mm": {
            "brand": "Generic",
            "name": '2" Spacer 7mm',
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 13,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_7_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 7.5mm',
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 14,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_8mm": {
            "brand": "Generic",
            "name": '2" Spacer 8mm',
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 14,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_8_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 8.5mm',
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 14,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_9mm": {
            "brand": "Generic",
            "name": '2" Spacer 9mm',
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 15,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_9_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 9.5mm',
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 15,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_11mm": {
            "brand": "Generic",
            "name": '2" Spacer 11mm',
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 16,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_12mm": {
            "brand": "Generic",
            "name": '2" Spacer 12mm',
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 17,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_13mm": {
            "brand": "Generic",
            "name": '2" Spacer 13mm',
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 18,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_14mm": {
            "brand": "Generic",
            "name": '2" Spacer 14mm',
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 19,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_16mm": {
            "brand": "Generic",
            "name": '2" Spacer 16mm',
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 20,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_17mm": {
            "brand": "Generic",
            "name": '2" Spacer 17mm',
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 21,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_18mm": {
            "brand": "Generic",
            "name": '2" Spacer 18mm',
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 22,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_22mm": {
            "brand": "Generic",
            "name": '2" Spacer 22mm',
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 25,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_1_25_Spacer_0_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_1mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_1_5mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_1_25_Spacer_2mm": {
            "brand": "Generic",
            "name": '1.25" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 4,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_0_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 0.5mm',
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_1mm": {
            "brand": "Generic",
            "name": '2" Spacer 1mm',
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_1_5mm": {
            "brand": "Generic",
            "name": '2" Spacer 1.5mm',
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_2_Spacer_2mm": {
            "brand": "Generic",
            "name": '2" Spacer 2mm',
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
}
