ADAPTERS = {
    "Generic_M42_M48_Adapter": {
            "brand": "Generic",
            "name": "M42→M48 Adapter",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 20,
            "tside_thread": "M48",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M48_M42_Adapter": {
            "brand": "Generic",
            "name": "M48→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 20,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M48",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_M54_Adapter": {
            "brand": "Generic",
            "name": "M42→M54 Adapter",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 25,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_M42_Adapter": {
            "brand": "Generic",
            "name": "M54→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 25,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_M68_Adapter": {
            "brand": "Generic",
            "name": "M42→M68 Adapter",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 35,
            "tside_thread": "M68",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M68_M42_Adapter": {
            "brand": "Generic",
            "name": "M68→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 35,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M68",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_5mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 16,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_10mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 18,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_15mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 19,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_20mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 21,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_25mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 22,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_30mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 24,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_40mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 27,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_50mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 30,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Canon_RF_M42_Adapter": {
            "brand": "Generic",
            "name": "Canon RF→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 25,
            "tside_thread": "Canon RF",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Sony_E_M42_Adapter": {
            "brand": "Generic",
            "name": "Sony E→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "Sony E",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Nikon_Z_M42_Adapter": {
            "brand": "Generic",
            "name": "Nikon Z→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 25,
            "tside_thread": "Nikon Z",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Fuji_X_M42_Adapter": {
            "brand": "Generic",
            "name": "Fuji X→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "Fuji X",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_MFT_M42_Adapter": {
            "brand": "Generic",
            "name": "MFT→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "MFT",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_Pentax_K_M42_Adapter": {
            "brand": "Generic",
            "name": "Pentax K→M42 Adapter",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 25,
            "tside_thread": "Pentax K",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_2_M42_Adapter": {
            "brand": "Generic",
            "name": '2"→M42 Adapter',
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 15,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_1_25_M42_Adapter": {
            "brand": "Generic",
            "name": '1.25"→M42 Adapter',
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 10,
            "tside_thread": '1.25"',
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_M42_Adapter_short": {
            "brand": "Generic",
            "name": "SC→M42 Adapter (short)",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 40,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_M42_Adapter_long": {
            "brand": "Generic",
            "name": "SC→M42 Adapter (long)",
            "type": "type_adapter",
            "optical_length": 45,
            "mass": 70,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Spacer_3mm": {
            "brand": "Generic",
            "name": "M42 Spacer 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 6,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 8,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_7mm": {
            "brand": "Generic",
            "name": "M42 Spacer 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 9,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_10mm": {
            "brand": "Generic",
            "name": "M42 Spacer 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 12,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_15mm": {
            "brand": "Generic",
            "name": "M42 Spacer 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 16,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_20mm": {
            "brand": "Generic",
            "name": "M42 Spacer 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 20,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_25mm": {
            "brand": "Generic",
            "name": "M42 Spacer 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 24,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_30mm": {
            "brand": "Generic",
            "name": "M42 Spacer 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 28,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_4mm": {
            "brand": "Generic",
            "name": "M42 Spacer 4mm",
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 7,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_6mm": {
            "brand": "Generic",
            "name": "M42 Spacer 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 8,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_8mm": {
            "brand": "Generic",
            "name": "M42 Spacer 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 10,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_12mm": {
            "brand": "Generic",
            "name": "M42 Spacer 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 13,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_35mm": {
            "brand": "Generic",
            "name": "M42 Spacer 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 32,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_40mm": {
            "brand": "Generic",
            "name": "M42 Spacer 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 36,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_50mm": {
            "brand": "Generic",
            "name": "M42 Spacer 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 44,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_2mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 2mm",
            "type": "type_adapter",
            "optical_length": 2,
            "mass": 12,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_3mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 12,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_7mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 14,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_8mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 14,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_12mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_35mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 22,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_45mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 45mm",
            "type": "type_adapter",
            "optical_length": 45,
            "mass": 25,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_60mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 60mm",
            "type": "type_adapter",
            "optical_length": 60,
            "mass": 30,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Male_Male_Ring": {
            "brand": "Generic",
            "name": "M42 Male-Male Ring",
            "type": "type_adapter",
            "optical_length": 2,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Male",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_9mm": {
            "brand": "Generic",
            "name": "M42 Spacer 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 11,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_14mm": {
            "brand": "Generic",
            "name": "M42 Spacer 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_17mm": {
            "brand": "Generic",
            "name": "M42 Spacer 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 17,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_22mm": {
            "brand": "Generic",
            "name": "M42 Spacer 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 21,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_28mm": {
            "brand": "Generic",
            "name": "M42 Spacer 28mm",
            "type": "type_adapter",
            "optical_length": 28,
            "mass": 26,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_45mm": {
            "brand": "Generic",
            "name": "M42 Spacer 45mm",
            "type": "type_adapter",
            "optical_length": 45,
            "mass": 40,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_2_1mm": {
            "brand": "Generic",
            "name": "M42 Spacer 2.1mm",
            "type": "type_adapter",
            "optical_length": 2.1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_2_3mm": {
            "brand": "Generic",
            "name": "M42 Spacer 2.3mm",
            "type": "type_adapter",
            "optical_length": 2.3,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_2_7mm": {
            "brand": "Generic",
            "name": "M42 Spacer 2.7mm",
            "type": "type_adapter",
            "optical_length": 2.7,
            "mass": 6,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_3_2mm": {
            "brand": "Generic",
            "name": "M42 Spacer 3.2mm",
            "type": "type_adapter",
            "optical_length": 3.2,
            "mass": 6,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_3_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 3.5mm",
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 6,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_4_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 4.5mm",
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 7,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_5_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 5.5mm",
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 8,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_6_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 6.5mm",
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 9,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_8_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 8.5mm",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 10,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_9_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 9.5mm",
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 11,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_11mm": {
            "brand": "Generic",
            "name": "M42 Spacer 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 12,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_13mm": {
            "brand": "Generic",
            "name": "M42 Spacer 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 14,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_16mm": {
            "brand": "Generic",
            "name": "M42 Spacer 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 16,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_18mm": {
            "brand": "Generic",
            "name": "M42 Spacer 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 18,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_19mm": {
            "brand": "Generic",
            "name": "M42 Spacer 19mm",
            "type": "type_adapter",
            "optical_length": 19,
            "mass": 19,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_21mm": {
            "brand": "Generic",
            "name": "M42 Spacer 21mm",
            "type": "type_adapter",
            "optical_length": 21,
            "mass": 20,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_23mm": {
            "brand": "Generic",
            "name": "M42 Spacer 23mm",
            "type": "type_adapter",
            "optical_length": 23,
            "mass": 22,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_24mm": {
            "brand": "Generic",
            "name": "M42 Spacer 24mm",
            "type": "type_adapter",
            "optical_length": 24,
            "mass": 23,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_26mm": {
            "brand": "Generic",
            "name": "M42 Spacer 26mm",
            "type": "type_adapter",
            "optical_length": 26,
            "mass": 24,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_27mm": {
            "brand": "Generic",
            "name": "M42 Spacer 27mm",
            "type": "type_adapter",
            "optical_length": 27,
            "mass": 25,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_29mm": {
            "brand": "Generic",
            "name": "M42 Spacer 29mm",
            "type": "type_adapter",
            "optical_length": 29,
            "mass": 27,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_32mm": {
            "brand": "Generic",
            "name": "M42 Spacer 32mm",
            "type": "type_adapter",
            "optical_length": 32,
            "mass": 29,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_33mm": {
            "brand": "Generic",
            "name": "M42 Spacer 33mm",
            "type": "type_adapter",
            "optical_length": 33,
            "mass": 30,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_36mm": {
            "brand": "Generic",
            "name": "M42 Spacer 36mm",
            "type": "type_adapter",
            "optical_length": 36,
            "mass": 32,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_37mm": {
            "brand": "Generic",
            "name": "M42 Spacer 37mm",
            "type": "type_adapter",
            "optical_length": 37,
            "mass": 33,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_38mm": {
            "brand": "Generic",
            "name": "M42 Spacer 38mm",
            "type": "type_adapter",
            "optical_length": 38,
            "mass": 34,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_42mm": {
            "brand": "Generic",
            "name": "M42 Spacer 42mm",
            "type": "type_adapter",
            "optical_length": 42,
            "mass": 37,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_44mm": {
            "brand": "Generic",
            "name": "M42 Spacer 44mm",
            "type": "type_adapter",
            "optical_length": 44,
            "mass": 39,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_46mm": {
            "brand": "Generic",
            "name": "M42 Spacer 46mm",
            "type": "type_adapter",
            "optical_length": 46,
            "mass": 40,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_48mm": {
            "brand": "Generic",
            "name": "M42 Spacer 48mm",
            "type": "type_adapter",
            "optical_length": 48,
            "mass": 42,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_6mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 13,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_9mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 14,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_11mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_13mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_14mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 16,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_16mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 16,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_17mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 17,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_18mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 17,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_22mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 18,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_28mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 28mm",
            "type": "type_adapter",
            "optical_length": 28,
            "mass": 20,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_55mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 55mm",
            "type": "type_adapter",
            "optical_length": 55,
            "mass": 28,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_75mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 75mm",
            "type": "type_adapter",
            "optical_length": 75,
            "mass": 34,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_Extension_Tube_100mm": {
            "brand": "Generic",
            "name": "M42 Extension Tube 100mm",
            "type": "type_adapter",
            "optical_length": 100,
            "mass": 42,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M42_to_T2_Adapter": {
            "brand": "Generic",
            "name": "M42 to T2 Adapter",
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 20,
            "tside_thread": "T2",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_M42_Spacer_0_5mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_1mm": {
            "brand": "Generic",
            "name": "M42 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_2mm": {
            "brand": "Generic",
            "name": "M42 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_3mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_1mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.1mm",
            "type": "type_spacer",
            "optical_length": 0.1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_15mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.15mm",
            "type": "type_spacer",
            "optical_length": 0.15,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_2mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.2mm",
            "type": "type_spacer",
            "optical_length": 0.2,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_25mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_35mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.35mm",
            "type": "type_spacer",
            "optical_length": 0.35,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_6mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_75mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_0_8mm": {
            "brand": "Generic",
            "name": "M42 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_1_1mm": {
            "brand": "Generic",
            "name": "M42 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_1_3mm": {
            "brand": "Generic",
            "name": "M42 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_1_7mm": {
            "brand": "Generic",
            "name": "M42 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_Spacer_1_9mm": {
            "brand": "Generic",
            "name": "M42 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 5,
            "tside_thread": "M42",
            "tside_gender": "",
            "cside_thread": "M42",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M42_to_T2_Adapter": {
            "brand": "Generic",
            "name": "M42 to T2 Adapter",
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 20,
            "tside_thread": "T2",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
