ADAPTERS = {
    "Generic_M54_M68_Adapter": {
            "brand": "Generic",
            "name": "M54→M68 Adapter",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 30,
            "tside_thread": "M68",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M68_M54_Adapter": {
            "brand": "Generic",
            "name": "M68→M54 Adapter",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 30,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M68",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_M72_Adapter": {
            "brand": "Generic",
            "name": "M54→M72 Adapter",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 35,
            "tside_thread": "M72",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M72_M54_Adapter": {
            "brand": "Generic",
            "name": "M72→M54 Adapter",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 35,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M72",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_M82_Adapter": {
            "brand": "Generic",
            "name": "M54→M82 Adapter",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 40,
            "tside_thread": "M82",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M82_M54_Adapter": {
            "brand": "Generic",
            "name": "M82→M54 Adapter",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 40,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M82",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_5mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 26,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_10mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 28,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_15mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 29,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_20mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 31,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_25mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 32,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_30mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 34,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_40mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 37,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_50mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 40,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_2_M54_Adapter": {
            "brand": "Generic",
            "name": '2"→M54 Adapter',
            "type": "type_adapter",
            "optical_length": 0,
            "mass": 25,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_M54_Adapter": {
            "brand": "Generic",
            "name": "SC→M54 Adapter",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 60,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Spacer_3mm": {
            "brand": "Generic",
            "name": "M54 Spacer 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 10,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 12,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_10mm": {
            "brand": "Generic",
            "name": "M54 Spacer 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 16,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_15mm": {
            "brand": "Generic",
            "name": "M54 Spacer 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 20,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_20mm": {
            "brand": "Generic",
            "name": "M54 Spacer 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 24,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_25mm": {
            "brand": "Generic",
            "name": "M54 Spacer 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 28,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_30mm": {
            "brand": "Generic",
            "name": "M54 Spacer 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 32,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_4mm": {
            "brand": "Generic",
            "name": "M54 Spacer 4mm",
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 11,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_7mm": {
            "brand": "Generic",
            "name": "M54 Spacer 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 13,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_8mm": {
            "brand": "Generic",
            "name": "M54 Spacer 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 14,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_12mm": {
            "brand": "Generic",
            "name": "M54 Spacer 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 17,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_35mm": {
            "brand": "Generic",
            "name": "M54 Spacer 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 36,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_40mm": {
            "brand": "Generic",
            "name": "M54 Spacer 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 40,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_2mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 2mm",
            "type": "type_adapter",
            "optical_length": 2,
            "mass": 20,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_3mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 20,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_7mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 22,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_8mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 22,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_12mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 23,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_35mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 30,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_45mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 45mm",
            "type": "type_adapter",
            "optical_length": 45,
            "mass": 33,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_60mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 60mm",
            "type": "type_adapter",
            "optical_length": 60,
            "mass": 38,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_M68_Adapter_short_2mm": {
            "brand": "Generic",
            "name": "M54→M68 Adapter (short, 2mm)",
            "type": "type_adapter",
            "optical_length": 2,
            "mass": 25,
            "tside_thread": "M68",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Male_Male_Ring": {
            "brand": "Generic",
            "name": "M54 Male-Male Ring",
            "type": "type_adapter",
            "optical_length": 2,
            "mass": 25,
            "tside_thread": "M54",
            "tside_gender": "Male",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_6mm": {
            "brand": "Generic",
            "name": "M54 Spacer 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 12,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_9mm": {
            "brand": "Generic",
            "name": "M54 Spacer 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 15,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_14mm": {
            "brand": "Generic",
            "name": "M54 Spacer 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 19,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_17mm": {
            "brand": "Generic",
            "name": "M54 Spacer 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 21,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_22mm": {
            "brand": "Generic",
            "name": "M54 Spacer 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 25,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_28mm": {
            "brand": "Generic",
            "name": "M54 Spacer 28mm",
            "type": "type_adapter",
            "optical_length": 28,
            "mass": 30,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_2_1mm": {
            "brand": "Generic",
            "name": "M54 Spacer 2.1mm",
            "type": "type_adapter",
            "optical_length": 2.1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_2_3mm": {
            "brand": "Generic",
            "name": "M54 Spacer 2.3mm",
            "type": "type_adapter",
            "optical_length": 2.3,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_2_7mm": {
            "brand": "Generic",
            "name": "M54 Spacer 2.7mm",
            "type": "type_adapter",
            "optical_length": 2.7,
            "mass": 10,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_3_2mm": {
            "brand": "Generic",
            "name": "M54 Spacer 3.2mm",
            "type": "type_adapter",
            "optical_length": 3.2,
            "mass": 10,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_3_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 3.5mm",
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 10,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_4_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 4.5mm",
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 11,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_5_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 5.5mm",
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 12,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_6_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 6.5mm",
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 13,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_7_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 7.5mm",
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 14,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_8_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 8.5mm",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 14,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_9_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 9.5mm",
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 15,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_11mm": {
            "brand": "Generic",
            "name": "M54 Spacer 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 16,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_13mm": {
            "brand": "Generic",
            "name": "M54 Spacer 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 18,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_16mm": {
            "brand": "Generic",
            "name": "M54 Spacer 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 20,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_18mm": {
            "brand": "Generic",
            "name": "M54 Spacer 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 22,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_19mm": {
            "brand": "Generic",
            "name": "M54 Spacer 19mm",
            "type": "type_adapter",
            "optical_length": 19,
            "mass": 23,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_21mm": {
            "brand": "Generic",
            "name": "M54 Spacer 21mm",
            "type": "type_adapter",
            "optical_length": 21,
            "mass": 24,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_23mm": {
            "brand": "Generic",
            "name": "M54 Spacer 23mm",
            "type": "type_adapter",
            "optical_length": 23,
            "mass": 26,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_24mm": {
            "brand": "Generic",
            "name": "M54 Spacer 24mm",
            "type": "type_adapter",
            "optical_length": 24,
            "mass": 27,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_26mm": {
            "brand": "Generic",
            "name": "M54 Spacer 26mm",
            "type": "type_adapter",
            "optical_length": 26,
            "mass": 28,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_27mm": {
            "brand": "Generic",
            "name": "M54 Spacer 27mm",
            "type": "type_adapter",
            "optical_length": 27,
            "mass": 29,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_6mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 21,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_9mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 22,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_11mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 23,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_13mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 23,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_14mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 24,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_16mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 24,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_17mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 25,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_18mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 25,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_22mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 26,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_28mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 28mm",
            "type": "type_adapter",
            "optical_length": 28,
            "mass": 28,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_55mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 55mm",
            "type": "type_adapter",
            "optical_length": 55,
            "mass": 36,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_75mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 75mm",
            "type": "type_adapter",
            "optical_length": 75,
            "mass": 42,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_M54_Extension_Tube_100mm": {
            "brand": "Generic",
            "name": "M54 Extension Tube 100mm",
            "type": "type_adapter",
            "optical_length": 100,
            "mass": 50,
            "tside_thread": "M54",
            "tside_gender": "Female",
            "cside_thread": "M54",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_M54_Spacer_0_5mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_1mm": {
            "brand": "Generic",
            "name": "M54 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_2mm": {
            "brand": "Generic",
            "name": "M54 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_3mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.3mm",
            "type": "type_spacer",
            "optical_length": 0.3,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_1mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.1mm",
            "type": "type_spacer",
            "optical_length": 0.1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_15mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.15mm",
            "type": "type_spacer",
            "optical_length": 0.15,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_2mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.2mm",
            "type": "type_spacer",
            "optical_length": 0.2,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_25mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.25mm",
            "type": "type_spacer",
            "optical_length": 0.25,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_35mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.35mm",
            "type": "type_spacer",
            "optical_length": 0.35,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_6mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.6mm",
            "type": "type_spacer",
            "optical_length": 0.6,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_75mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.75mm",
            "type": "type_spacer",
            "optical_length": 0.75,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_0_8mm": {
            "brand": "Generic",
            "name": "M54 Spacer 0.8mm",
            "type": "type_spacer",
            "optical_length": 0.8,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_1_1mm": {
            "brand": "Generic",
            "name": "M54 Spacer 1.1mm",
            "type": "type_spacer",
            "optical_length": 1.1,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_1_3mm": {
            "brand": "Generic",
            "name": "M54 Spacer 1.3mm",
            "type": "type_spacer",
            "optical_length": 1.3,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_1_7mm": {
            "brand": "Generic",
            "name": "M54 Spacer 1.7mm",
            "type": "type_spacer",
            "optical_length": 1.7,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M54_Spacer_1_9mm": {
            "brand": "Generic",
            "name": "M54 Spacer 1.9mm",
            "type": "type_spacer",
            "optical_length": 1.9,
            "mass": 9,
            "tside_thread": "M54",
            "tside_gender": "",
            "cside_thread": "M54",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
}
