ADAPTERS = {
    "Generic_Eyepiece_Projection_Adapter_2": {
            "brand": "Generic",
            "name": 'Eyepiece Projection Adapter (2")',
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 80,
            "tside_thread": '2"',
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T_Thread_Extension_10mm": {
            "brand": "Generic",
            "name": "T-Thread Extension 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 15,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T_Thread_Extension_30mm": {
            "brand": "Generic",
            "name": "T-Thread Extension 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 25,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T_Thread_Extension_50mm": {
            "brand": "Generic",
            "name": "T-Thread Extension 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 35,
            "tside_thread": "M42",
            "tside_gender": "Female",
            "cside_thread": "M42",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_T_Ring_Canon_EOS": {
            "brand": "Generic",
            "name": "T-Ring for Canon EOS",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 40,
            "tside_thread": "T2",
            "tside_gender": "Female",
            "cside_thread": "EOS",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_T_Ring_Canon_EOS": {
            "brand": "Generic",
            "name": "T-Ring for Canon EOS",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 40,
            "tside_thread": "T2",
            "tside_gender": "Female",
            "cside_thread": "EOS",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
