ADAPTERS = {
    "Generic_SC_2_Adapter": {
            "brand": "Generic",
            "name": 'SC→2" Adapter',
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 80,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_3mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 22,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 24,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_7mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 25,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_10mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 28,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_15mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 32,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_20mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 36,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_25mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 40,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_30mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 44,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_40mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 52,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_50mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 60,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Visual_Back_1_25": {
            "brand": "Generic",
            "name": 'SC Visual Back (1.25")',
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 45,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": '1.25"',
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Visual_Back_2": {
            "brand": "Generic",
            "name": 'SC Visual Back (2")',
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 70,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": '2"',
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_2_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 2.5mm",
            "type": "type_adapter",
            "optical_length": 2.5,
            "mass": 22,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_3_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 3.5mm",
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 22,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_4_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 4.5mm",
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 23,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_5_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 5.5mm",
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 24,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_6mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 24,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_6_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 6.5mm",
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 25,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_7_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 7.5mm",
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 26,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_8mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 26,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_8_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 8.5mm",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 26,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_9mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 27,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_9_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 9.5mm",
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 27,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_11mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 28,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_12mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 29,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_13mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 30,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_14mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 31,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_16mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 32,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_17mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 33,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_18mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 34,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_22mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 37,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_28mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 28mm",
            "type": "type_adapter",
            "optical_length": 28,
            "mass": 42,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_35mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 48,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_45mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 45mm",
            "type": "type_adapter",
            "optical_length": 45,
            "mass": 56,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_55mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 55mm",
            "type": "type_adapter",
            "optical_length": 55,
            "mass": 64,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_60mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 60mm",
            "type": "type_adapter",
            "optical_length": 60,
            "mass": 68,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_5mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 19,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_10mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_15mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 22,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_20mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 24,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_25mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 25,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_30mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 30mm",
            "type": "type_adapter",
            "optical_length": 30,
            "mass": 27,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_35mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 35mm",
            "type": "type_adapter",
            "optical_length": 35,
            "mass": 28,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_40mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 40mm",
            "type": "type_adapter",
            "optical_length": 40,
            "mass": 30,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_50mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 50mm",
            "type": "type_adapter",
            "optical_length": 50,
            "mass": 33,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_60mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 60mm",
            "type": "type_adapter",
            "optical_length": 60,
            "mass": 36,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
    "Generic_SC_Extension_Tube_75mm": {
            "brand": "Generic",
            "name": "SC Extension Tube 75mm",
            "type": "type_adapter",
            "optical_length": 75,
            "mass": 40,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "Female",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "Male",
            "reversible": False,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_SC_Schmidt_Cassegrain_Spacer_1mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_2mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_0_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_SC_Schmidt_Cassegrain_Spacer_1_5mm": {
            "brand": "Generic",
            "name": "SC (Schmidt-Cassegrain) Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 21,
            "tside_thread": "SC (Schmidt-Cassegrain)",
            "tside_gender": "",
            "cside_thread": "SC (Schmidt-Cassegrain)",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
}
