ADAPTERS = {
    "Generic_M56_Spacer_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 12,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_10mm": {
            "brand": "Generic",
            "name": "M56 Spacer 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 16,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_15mm": {
            "brand": "Generic",
            "name": "M56 Spacer 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 20,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_20mm": {
            "brand": "Generic",
            "name": "M56 Spacer 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 24,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 5mm",
            "type": "type_adapter",
            "optical_length": 5,
            "mass": 14,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_10mm": {
            "brand": "Generic",
            "name": "M63 Spacer 10mm",
            "type": "type_adapter",
            "optical_length": 10,
            "mass": 18,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_15mm": {
            "brand": "Generic",
            "name": "M63 Spacer 15mm",
            "type": "type_adapter",
            "optical_length": 15,
            "mass": 22,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_20mm": {
            "brand": "Generic",
            "name": "M63 Spacer 20mm",
            "type": "type_adapter",
            "optical_length": 20,
            "mass": 26,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_2_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 2.5mm",
            "type": "type_adapter",
            "optical_length": 2.5,
            "mass": 10,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_3mm": {
            "brand": "Generic",
            "name": "M56 Spacer 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 10,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_3_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 3.5mm",
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 10,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_4mm": {
            "brand": "Generic",
            "name": "M56 Spacer 4mm",
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 11,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_4_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 4.5mm",
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 11,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_5_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 5.5mm",
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 12,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_6mm": {
            "brand": "Generic",
            "name": "M56 Spacer 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 12,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_6_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 6.5mm",
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 13,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_7mm": {
            "brand": "Generic",
            "name": "M56 Spacer 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 13,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_7_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 7.5mm",
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 14,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_8mm": {
            "brand": "Generic",
            "name": "M56 Spacer 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 14,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_8_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 8.5mm",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 14,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_9mm": {
            "brand": "Generic",
            "name": "M56 Spacer 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 15,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_9_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 9.5mm",
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 15,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_11mm": {
            "brand": "Generic",
            "name": "M56 Spacer 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 16,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_12mm": {
            "brand": "Generic",
            "name": "M56 Spacer 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 17,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_13mm": {
            "brand": "Generic",
            "name": "M56 Spacer 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 18,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_14mm": {
            "brand": "Generic",
            "name": "M56 Spacer 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 19,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_16mm": {
            "brand": "Generic",
            "name": "M56 Spacer 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 20,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_17mm": {
            "brand": "Generic",
            "name": "M56 Spacer 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 21,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_18mm": {
            "brand": "Generic",
            "name": "M56 Spacer 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 22,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_22mm": {
            "brand": "Generic",
            "name": "M56 Spacer 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 25,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_25mm": {
            "brand": "Generic",
            "name": "M56 Spacer 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 28,
            "tside_thread": "M56",
            "tside_gender": "Female",
            "cside_thread": "M56",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_2_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 2.5mm",
            "type": "type_adapter",
            "optical_length": 2.5,
            "mass": 12,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_3mm": {
            "brand": "Generic",
            "name": "M63 Spacer 3mm",
            "type": "type_adapter",
            "optical_length": 3,
            "mass": 12,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_3_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 3.5mm",
            "type": "type_adapter",
            "optical_length": 3.5,
            "mass": 12,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_4mm": {
            "brand": "Generic",
            "name": "M63 Spacer 4mm",
            "type": "type_adapter",
            "optical_length": 4,
            "mass": 13,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_4_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 4.5mm",
            "type": "type_adapter",
            "optical_length": 4.5,
            "mass": 13,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_5_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 5.5mm",
            "type": "type_adapter",
            "optical_length": 5.5,
            "mass": 14,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_6mm": {
            "brand": "Generic",
            "name": "M63 Spacer 6mm",
            "type": "type_adapter",
            "optical_length": 6,
            "mass": 14,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_6_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 6.5mm",
            "type": "type_adapter",
            "optical_length": 6.5,
            "mass": 15,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_7mm": {
            "brand": "Generic",
            "name": "M63 Spacer 7mm",
            "type": "type_adapter",
            "optical_length": 7,
            "mass": 15,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_7_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 7.5mm",
            "type": "type_adapter",
            "optical_length": 7.5,
            "mass": 16,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_8mm": {
            "brand": "Generic",
            "name": "M63 Spacer 8mm",
            "type": "type_adapter",
            "optical_length": 8,
            "mass": 16,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_8_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 8.5mm",
            "type": "type_adapter",
            "optical_length": 8.5,
            "mass": 16,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_9mm": {
            "brand": "Generic",
            "name": "M63 Spacer 9mm",
            "type": "type_adapter",
            "optical_length": 9,
            "mass": 17,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_9_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 9.5mm",
            "type": "type_adapter",
            "optical_length": 9.5,
            "mass": 17,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_11mm": {
            "brand": "Generic",
            "name": "M63 Spacer 11mm",
            "type": "type_adapter",
            "optical_length": 11,
            "mass": 18,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_12mm": {
            "brand": "Generic",
            "name": "M63 Spacer 12mm",
            "type": "type_adapter",
            "optical_length": 12,
            "mass": 19,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_13mm": {
            "brand": "Generic",
            "name": "M63 Spacer 13mm",
            "type": "type_adapter",
            "optical_length": 13,
            "mass": 20,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_14mm": {
            "brand": "Generic",
            "name": "M63 Spacer 14mm",
            "type": "type_adapter",
            "optical_length": 14,
            "mass": 21,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_16mm": {
            "brand": "Generic",
            "name": "M63 Spacer 16mm",
            "type": "type_adapter",
            "optical_length": 16,
            "mass": 22,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_17mm": {
            "brand": "Generic",
            "name": "M63 Spacer 17mm",
            "type": "type_adapter",
            "optical_length": 17,
            "mass": 23,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_18mm": {
            "brand": "Generic",
            "name": "M63 Spacer 18mm",
            "type": "type_adapter",
            "optical_length": 18,
            "mass": 24,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_22mm": {
            "brand": "Generic",
            "name": "M63 Spacer 22mm",
            "type": "type_adapter",
            "optical_length": 22,
            "mass": 27,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_25mm": {
            "brand": "Generic",
            "name": "M63 Spacer 25mm",
            "type": "type_adapter",
            "optical_length": 25,
            "mass": 30,
            "tside_thread": "M63",
            "tside_gender": "Female",
            "cside_thread": "M63",
            "cside_gender": "Male",
            "reversible": True,
            "bf_role": "",
        },
}
SPACERS = {
    "Generic_M56_Spacer_1mm": {
            "brand": "Generic",
            "name": "M56 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_2mm": {
            "brand": "Generic",
            "name": "M56 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_1mm": {
            "brand": "Generic",
            "name": "M63 Spacer 1mm",
            "type": "type_spacer",
            "optical_length": 1,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_2mm": {
            "brand": "Generic",
            "name": "M63 Spacer 2mm",
            "type": "type_spacer",
            "optical_length": 2,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_0_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_0_7mm": {
            "brand": "Generic",
            "name": "M56 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M56_Spacer_1_5mm": {
            "brand": "Generic",
            "name": "M56 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 9,
            "tside_thread": "M56",
            "tside_gender": "",
            "cside_thread": "M56",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_0_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 0.5mm",
            "type": "type_spacer",
            "optical_length": 0.5,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_0_7mm": {
            "brand": "Generic",
            "name": "M63 Spacer 0.7mm",
            "type": "type_spacer",
            "optical_length": 0.7,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
    "Generic_M63_Spacer_1_5mm": {
            "brand": "Generic",
            "name": "M63 Spacer 1.5mm",
            "type": "type_spacer",
            "optical_length": 1.5,
            "mass": 11,
            "tside_thread": "M63",
            "tside_gender": "",
            "cside_thread": "M63",
            "cside_gender": "",
            "reversible": True,
            "bf_role": "",
        },
}
